"""empty message

Revision ID: 01c8da270e30
Revises: 5345ad7480a5
Create Date: 2020-12-05 18:31:31.417451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c8da270e30'
down_revision = '5345ad7480a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
