"""empty message

Revision ID: 16707c0e5768
Revises: d00d39af8a27
Create Date: 2020-12-13 12:50:12.076360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16707c0e5768'
down_revision = 'd00d39af8a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followed_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_followed_number'), 'users', ['followed_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_followed_number'), table_name='users')
    op.drop_column('users', 'followed_number')
    # ### end Alembic commands ###
