"""empty message

Revision ID: 1af2422a52ca
Revises: bd03deacfa63
Create Date: 2020-12-12 12:43:23.911743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af2422a52ca'
down_revision = 'bd03deacfa63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('file_old_name', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_tools_file_old_name'), 'tools', ['file_old_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_file_old_name'), table_name='tools')
    op.drop_column('tools', 'file_old_name')
    # ### end Alembic commands ###
