"""empty message

Revision ID: 5345ad7480a5
Revises: 87cb86f86442
Create Date: 2020-12-05 18:28:03.763594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5345ad7480a5'
down_revision = '87cb86f86442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('province', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'province')
    op.drop_column('users', 'city')
    op.drop_column('users', 'area')
    # ### end Alembic commands ###
