"""empty message

Revision ID: 703259c29d29
Revises: 7cb83f1b02b0
Create Date: 2020-12-06 20:36:36.107594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703259c29d29'
down_revision = '7cb83f1b02b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('introduction', sa.String(length=100), nullable=True))
    op.add_column('tools', sa.Column('title', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_tools_title'), 'tools', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_title'), table_name='tools')
    op.drop_column('tools', 'title')
    op.drop_column('tools', 'introduction')
    # ### end Alembic commands ###
