"""empty message

Revision ID: 727813a16dc0
Revises: 3a1f7545a80d
Create Date: 2020-11-18 22:33:08.024371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727813a16dc0'
down_revision = '3a1f7545a80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
