"""empty message

Revision ID: 8b0851da8555
Revises: dd41d12f9340
Create Date: 2020-12-06 21:43:09.702436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0851da8555'
down_revision = 'dd41d12f9340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'introduction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('introduction', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
