"""empty message

Revision ID: a241744a546c
Revises: 1af2422a52ca
Create Date: 2020-12-12 15:50:59.001999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a241744a546c'
down_revision = '1af2422a52ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pictures_file_name'), 'pictures', ['file_name'], unique=False)
    op.create_index(op.f('ix_pictures_tool_id'), 'pictures', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pictures_tool_id'), table_name='pictures')
    op.drop_index(op.f('ix_pictures_file_name'), table_name='pictures')
    op.drop_table('pictures')
    # ### end Alembic commands ###
