"""empty message

Revision ID: bd03deacfa63
Revises: ec997a16c2ea
Create Date: 2020-12-10 15:04:31.882748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd03deacfa63'
down_revision = 'ec997a16c2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('contents_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'contents_html')
    # ### end Alembic commands ###
