"""empty message

Revision ID: d00d39af8a27
Revises: 22c8fb1f028d
Create Date: 2020-12-13 12:00:38.186801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00d39af8a27'
down_revision = '22c8fb1f028d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fans_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_fans_number'), 'users', ['fans_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_fans_number'), table_name='users')
    op.drop_column('users', 'fans_number')
    # ### end Alembic commands ###
