"""empty message

Revision ID: d8e5d9fecbaa
Revises: 01c8da270e30
Create Date: 2020-12-06 11:30:55.455463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e5d9fecbaa'
down_revision = '01c8da270e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['avatar_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar_name')
    # ### end Alembic commands ###
