"""empty message

Revision ID: dd41d12f9340
Revises: 703259c29d29
Create Date: 2020-12-06 20:44:12.020895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd41d12f9340'
down_revision = '703259c29d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('upload_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comment_upload_time'), 'comment', ['upload_time'], unique=False)
    op.add_column('tools', sa.Column('upload_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tools_upload_time'), 'tools', ['upload_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_upload_time'), table_name='tools')
    op.drop_column('tools', 'upload_time')
    op.drop_index(op.f('ix_comment_upload_time'), table_name='comment')
    op.drop_column('comment', 'upload_time')
    # ### end Alembic commands ###
